### PR TITLE
Feat update sdk

### PR DESCRIPTION
**Pull request by hookthebot**
updated SDK to v0.10.x+
removed migrations and its tooling as its not longer required in newer SDK version

### CODE REVIEW

**Comment by yevgenypats** [comment]
Hi Team, We deprecated migrations to to the overhead it introduced and other potential features it blocked us from delivering. We saw that you actually upgraded to the sdk and we broke it again so we created a new PR to help you upgrade. I'll try also test it as I created a trial yandex cloud account.

**Comment by yevgenypats** [comment]
Forgot to link to our blog - https://www.cloudquery.io/blog/migration-and-history-deprecation

**Comment by toufreach5** [comment]
Hello,

Could you please look a it please ?

Thanks.

**Comment by toufreach5** [comment]
Hello, 

any update on this ?

Thanks.

**Comment by daniil-ushkov** [comment]
Updated golang version in local tests to pass it and merged from another [PR](https://github.com/yandex-cloud/cq-provider-yandex/pull/14).

**Pull request merged**
